### ISSUE TITLE
Number of Taxa

### ISSUE THREAD

**Issue by rikchard4411** [rbouckaert/starbeast3#1]
good morning,

I have two doubts regarding the use of Starbeast.

1. What is the maximum number of taxa that can be analyzed in Starbeast?

2. Is it necessary for all taxa to have the same number of molecular markers to estimate divergence times in Starbeast?

I ask these questions because I am currently working with over 400 species of salamanders.

Thanks in advance, I look forward to a prompt response to this question.

**Comment by jordandouglas** [comment]
Hi - sorry for the delayed response, I was not receiving notifcations on this page. 

1. It's hard to answer the upper limit on the number of taxa. I would not want to go over several hundred. It also depends on how many gene trees. I would suggest testing out on the full dataset and if it takes too long then try subsampling down to 200 / 150 / 100 etc until it starts to seem tractable

2. No - you do not need all taxa to have the same number of markers. Missing data is okay. 

Jordan
