### ISSUE TITLE
Bmodeltest and ORC 

### ISSUE THREAD

**Issue by joqb** [rbouckaert/starbeast3#2]
Hi,

Just a quick question, I was not able to get bmodeltest and ORC to run with starbeast3, is this normal? Will it be considered in the future?

Cheers

**Comment by jordandouglas** [comment]
Hi, ORC runs by default as part of starbeast3's multispecies relaxed clock model. There is no need to select the ORC model as it is automatic. bModelTest is now part of starbeast3, but only for beast 2.7
