### ISSUE TITLE
Tip Dating in Starbeast3

### ISSUE THREAD

**Issue by johnpatramanis** [rbouckaert/starbeast3#3]
Good day, I would like to run a tip-dated tree analysis. In previous versions of BEAST and starBEAST there used to be a tip-dating tab, which now seems to be missing. I have 2 questions though:

1) Is there any way to run a tip dated tree with starbeast3 right now?
2) Is tip-dating appropriate for samples that are litterally sampled in the past? (e.g. ancient DNA or ancient Protein data). So far it seems all guides talk about adding an empty entry as a tip dated sample.

Thank you very much in advance and hope you keep up the great work!

**Comment by jordandouglas** [comment]
Hi, thank you for your feedback

1. We are restoring this feature right now, it will be available in the new starbeast3 release (v1.1.4)
2. If you have ancient DNA then tip-dating is appropriate for that. The tip dating assumes that the age of the species is the same as the age of all of its genes

**Comment by johnpatramanis** [comment]
Thank you very much!
I can close the issue or I can leave it here for people to see.
